version: "3.9"

services:
  dev_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: BACKDOCK_DEV
    environment:
      NODE_ENV: dev_
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_NAME: adquisiciones
      API_VER: ${API_VER}
      API_HOST: localhost
    ports:
      - "3050:3050"
    depends_on:
      - mongodb

  tst_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: BACKDOCK_TST
    environment:
      NODE_ENV: tst_
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_NAME: adquisiciones
      API_VER: ${API_VER}
      API_HOST: localhost
    ports:
      - "3040:3040"
    depends_on:
      - mongodb

  prd_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: BACKDOCK_PRD
    environment:
      NODE_ENV: prd_
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_NAME: adquisiciones
      API_VER: ${API_VER}
      API_HOST: localhost
    ports:
      - "3030:3030"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5
    container_name: MONGODOCK
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
